using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MyMusic.Infrastructure.Persistence.Migrations;

/// <inheritdoc />
public partial class CreateCountryTable : Migration
{
    /// <inheritdoc />
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.CreateTable(
            name: "country",
            columns: table => new
            {
                id = table.Column<int>(type: "integer", nullable: false)
                    .Annotation(
                        "Npgsql:ValueGenerationStrategy",
                        NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                country_name = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: false),
                country_code = table.Column<string>(type: "character varying(3)", maxLength: 3, nullable: false)
            },
            constraints: table =>
            {
                table.PrimaryKey("PK_country", x => x.id);
            });

        migrationBuilder.CreateIndex(
            name: "IX_country_country_code",
            table: "country",
            column: "country_code",
            unique: true);

        migrationBuilder.InsertData(
            table: "country",
            columns: new[] { "country_name", "country_code" },
            values: new object[,]
            {
                { "Ägypten", "EG" },
                { "Albanien", "AL" },
                { "Algerien", "DZ" },
                { "Andorra", "AD" },
                { "Angola", "AO" },
                { "Anguilla", "AI" },
                { "Antarktis", "AQ" },
                { "Antigua und Barbuda", "AG" },
                { "Äquatorial Guinea", "GQ" },
                { "Argentinien", "AR" },
                { "Armenien", "AM" },
                { "Aruba", "AW" },
                { "Aserbaidschan", "AZ" },
                { "Äthiopien", "ET" },
                { "Australien", "AU" },
                { "Bahamas", "BS" },
                { "Bahrain", "BH" },
                { "Bangladesh", "BD" },
                { "Barbados", "BB" },
                { "Belgien", "BE" },
                { "Belize", "BZ" },
                { "Benin", "BJ" },
                { "Bermudas", "BM" },
                { "Bhutan", "BT" },
                { "Birma", "MM" },
                { "Bolivien", "BO" },
                { "Bosnien-Herzegowina", "BA" },
                { "Botswana", "BW" },
                { "Bouvet Inseln", "BV" },
                { "Brasilien", "BR" },
                { "Britisch-Indischer Ozean", "IO" },
                { "Brunei", "BN" },
                { "Bulgarien", "BG" },
                { "Burkina Faso", "BF" },
                { "Burundi", "BI" },
                { "Chile", "CL" },
                { "China", "CN" },
                { "Christmas Island", "CX" },
                { "Cook Inseln", "CK" },
                { "Costa Rica", "CR" },
                { "Dänemark", "DK" },
                { "Deutschland", "DE" },
                { "Djibuti", "DJ" },
                { "Dominika", "DM" },
                { "Dominikanische Republik", "DO" },
                { "Ecuador", "EC" },
                { "El Salvador", "SV" },
                { "Elfenbeinküste", "CI" },
                { "Eritrea", "ER" },
                { "Estland", "EE" },
                { "Falkland Inseln", "FK" },
                { "Färöer Inseln", "FO" },
                { "Fidschi", "FJ" },
                { "Finnland", "FI" },
                { "Frankreich", "FR" },
                { "französisch Guyana", "GF" },
                { "Französisch Polynesien", "PF" },
                { "Französisches Süd-Territorium", "TF" },
                { "Gabun", "GA" },
                { "Gambia", "GM" },
                { "Georgien", "GE" },
                { "Ghana", "GH" },
                { "Gibraltar", "GI" },
                { "Grenada", "GD" },
                { "Griechenland", "GR" },
                { "Grönland", "GL" },
                { "Grossbritannien (UK)", "GB" },
                { "Guadeloupe", "GP" },
                { "Guam", "GU" },
                { "Guatemala", "GT" },
                { "Guinea", "GN" },
                { "Guinea Bissau", "GW" },
                { "Guyana", "GY" },
                { "Haiti", "HT" },
                { "Heard und McDonald Islands", "HM" },
                { "Honduras", "HN" },
                { "Hong Kong", "HK" },
                { "Indien", "IN" },
                { "Indonesien", "ID" },
                { "Irak", "IQ" },
                { "Iran", "IR" },
                { "Irland", "IE" },
                { "Island", "IS" },
                { "Israel", "IL" },
                { "Italien", "IT" },
                { "Jamaika", "JM" },
                { "Japan", "JP" },
                { "Jemen", "YE" },
                { "Jordanien", "JO" },
                { "Jugoslawien", "YU" },
                { "Kaiman Inseln", "KY" },
                { "Kambodscha", "KH" },
                { "Kamerun", "CM" },
                { "Kanada", "CA" },
                { "Kap Verde", "CV" },
                { "Kasachstan", "KZ" },
                { "Kenia", "KE" },
                { "Kirgisistan", "KG" },
                { "Kiribati", "KI" },
                { "Kokosinseln", "CC" },
                { "Kolumbien", "CO" },
                { "Komoren", "KM" },
                { "Kongo", "CG" },
                { "Kongo, Demokratische Republik", "CD" },
                { "Kroatien", "HR" },
                { "Kuba", "CU" },
                { "Kuwait", "KW" },
                { "Laos", "LA" },
                { "Lesotho", "LS" },
                { "Lettland", "LV" },
                { "Libanon", "LB" },
                { "Liberia", "LR" },
                { "Libyen", "LY" },
                { "Liechtenstein", "LI" },
                { "Litauen", "LT" },
                { "Luxemburg", "LU" },
                { "Macao", "MO" },
                { "Madagaskar", "MG" },
                { "Malawi", "MW" },
                { "Malaysia", "MY" },
                { "Malediven", "MV" },
                { "Mali", "ML" },
                { "Malta", "MT" },
                { "Marianen", "MP" },
                { "Marokko", "MA" },
                { "Marshall Inseln", "MH" },
                { "Martinique", "MQ" },
                { "Mauretanien", "MR" },
                { "Mauritius", "MU" },
                { "Mayotte", "YT" },
                { "Mazedonien", "MK" },
                { "Mexiko", "MX" },
                { "Mikronesien", "FM" },
                { "Mocambique", "MZ" },
                { "Moldavien", "MD" },
                { "Monaco", "MC" },
                { "Mongolei", "MN" },
                { "Montserrat", "MS" },
                { "Namibia", "NA" },
                { "Nauru", "NR" },
                { "Nepal", "NP" },
                { "Neukaledonien", "NC" },
                { "Neuseeland", "NZ" },
                { "Nicaragua", "NI" },
                { "Niederlande", "NL" },
                { "Niederländische Antillen", "AN" },
                { "Niger", "NE" },
                { "Nigeria", "NG" },
                { "Niue", "NU" },
                { "Nord Korea", "KP" },
                { "Norfolk Inseln", "NF" },
                { "Norwegen", "NO" },
                { "Oman", "OM" },
                { "Österreich", "AT" },
                { "Pakistan", "PK" },
                { "Palästina", "PS" },
                { "Palau", "PW" },
                { "Panama", "PA" },
                { "Papua Neuguinea", "PG" },
                { "Paraguay", "PY" },
                { "Peru", "PE" },
                { "Philippinen", "PH" },
                { "Pitcairn", "PN" },
                { "Polen", "PL" },
                { "Portugal", "PT" },
                { "Puerto Rico", "PR" },
                { "Qatar", "QA" },
                { "Reunion", "RE" },
                { "Ruanda", "RW" },
                { "Rumänien", "RO" },
                { "Russland", "RU" },
                { "Saint Lucia", "LC" },
                { "Sambia", "ZM" },
                { "Amerikanisch-Samoa", "AS" },
                { "Samoa", "WS" },
                { "San Marino", "SM" },
                { "Sao Tome", "ST" },
                { "Saudi Arabien", "SA" },
                { "Schweden", "SE" },
                { "Schweiz", "CH" },
                { "Senegal", "SN" },
                { "Seychellen", "SC" },
                { "Sierra Leone", "SL" },
                { "Singapur", "SG" },
                { "Slowakei -slowakische Republik-", "SK" },
                { "Slowenien", "SI" },
                { "Solomon Inseln", "SB" },
                { "Somalia", "SO" },
                { "South Georgia, South Sandwich Isl.", "GS" },
                { "Spanien", "ES" },
                { "Sri Lanka", "LK" },
                { "St. Helena", "SH" },
                { "St. Kitts Nevis Anguilla", "KN" },
                { "St. Pierre und Miquelon", "PM" },
                { "St. Vincent", "VC" },
                { "Süd Korea", "KR" },
                { "Südafrika", "ZA" },
                { "Sudan", "SD" },
                { "Surinam", "SR" },
                { "Svalbard und Jan Mayen Islands", "SJ" },
                { "Swasiland", "SZ" },
                { "Syrien", "SY" },
                { "Tadschikistan", "TJ" },
                { "Taiwan", "TW" },
                { "Tansania", "TZ" },
                { "Thailand", "TH" },
                { "Timor", "TP" },
                { "Togo", "TG" },
                { "Tokelau", "TK" },
                { "Tonga", "TO" },
                { "Trinidad Tobago", "TT" },
                { "Tschad", "TD" },
                { "Tschechische Republik", "CZ" },
                { "Tunesien", "TN" },
                { "Türkei", "TR" },
                { "Turkmenistan", "TM" },
                { "Turks und Kaikos Inseln", "TC" },
                { "Tuvalu", "TV" },
                { "Uganda", "UG" },
                { "Ukraine", "UA" },
                { "Ungarn", "HU" },
                { "Uruguay", "UY" },
                { "Usbekistan", "UZ" },
                { "Vanuatu", "VU" },
                { "Vatikan", "VA" },
                { "Venezuela", "VE" },
                { "Vereinigte Arabische Emirate", "AE" },
                { "Vereinigte Staaten von Amerika", "US" },
                { "Vietnam", "VN" },
                { "Virgin Island (Brit.)", "VG" },
                { "Virgin Island (USA)", "VI" },
                { "Wallis et Futuna", "WF" },
                { "Weissrussland", "BY" },
                { "Westsahara", "EH" },
                { "Zentralafrikanische Republik", "CF" },
                { "Zimbabwe", "ZW" },
                { "Zypern", "CY" },
                { "Unbekannt", "---" },
            });
    }

    /// <inheritdoc />
    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropTable(
            name: "country");
    }
}
