// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyMusic.Domain.DomainModels.Sammlung.Record;
using MyMusic.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MyMusic.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MyMusicDbContext))]
    [Migration("20260831134945_AddCollectionNumberToRecord")]
    partial class AddCollectionNumberToRecord
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "record_condition", new[] { "Mint", "NM", "VG+", "VG", "G+", "G", "P" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "record_format", new[] { "Album", "MaxiSingle", "Single", "EP", "Compilation", "CD-Album", "CD-MaxiSingle", "CD-Single", "CD-EP", "CD-Compilation" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MyMusic.Domain.DomainModels.Sammlung.Record.Record", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("AlbumCover")
                        .HasColumnType("bytea")
                        .HasColumnName("album_cover");

                    b.Property<string>("AlbumName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("album_name");

                    b.Property<int?>("ArtistId")
                        .HasColumnType("integer")
                        .HasColumnName("artist_id");

                    b.Property<int>("CollectionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("collection_number");

                    b.Property<RecordCondition>("Condition")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("record_condition")
                        .HasColumnName("condition")
                        .HasDefaultValueSql("'VG'::record_condition");

                    b.Property<RecordFormat>("Format")
                        .HasColumnType("record_format")
                        .HasColumnName("format");

                    b.Property<string>("Information")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("information");

                    b.Property<int>("LabelId")
                        .HasColumnType("integer")
                        .HasColumnName("label_id");

                    b.Property<short>("ReleaseYear")
                        .HasColumnType("smallint")
                        .HasColumnName("release_year");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.HasIndex("LabelId");

                    b.HasIndex("UserId", "CollectionNumber")
                        .IsUnique();

                    b.ToTable("record", (string)null);
                });

            modelBuilder.Entity("MyMusic.Domain.DomainModels.Sammlung.RecordTrack.RecordTrack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArtistId")
                        .HasColumnType("integer")
                        .HasColumnName("artist_id");

                    b.Property<int>("GenreId")
                        .HasColumnType("integer")
                        .HasColumnName("genre_id");

                    b.Property<string>("Information")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("information");

                    b.Property<int>("RecordId")
                        .HasColumnType("integer")
                        .HasColumnName("record_id");

                    b.Property<string>("RecordSide")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasDefaultValue("0")
                        .HasColumnName("record_side");

                    b.Property<string>("TrackName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("track_name");

                    b.Property<short>("TrackNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("track_number");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.HasIndex("GenreId");

                    b.HasIndex("RecordId", "RecordSide", "TrackNumber")
                        .IsUnique();

                    b.ToTable("record_track", (string)null);
                });

            modelBuilder.Entity("MyMusic.Domain.DomainModels.Stammdaten.Artist.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("artist_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Name")
                        .IsUnique();

                    b.ToTable("artist", (string)null);
                });

            modelBuilder.Entity("MyMusic.Domain.DomainModels.Stammdaten.Country.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("country_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("country_name");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("country", (string)null);
                });

            modelBuilder.Entity("MyMusic.Domain.DomainModels.Stammdaten.Genre.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("genre");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Name")
                        .IsUnique();

                    b.ToTable("genre", (string)null);
                });

            modelBuilder.Entity("MyMusic.Domain.DomainModels.Stammdaten.Label.Label", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CountryId")
                        .HasColumnType("integer")
                        .HasColumnName("country_id");

                    b.Property<string>("Information")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("information");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("label_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("UserId", "Name")
                        .IsUnique();

                    b.ToTable("label", (string)null);
                });

            modelBuilder.Entity("MyMusic.Domain.DomainModels.Sammlung.Record.Record", b =>
                {
                    b.HasOne("MyMusic.Domain.DomainModels.Stammdaten.Artist.Artist", null)
                        .WithMany()
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MyMusic.Domain.DomainModels.Stammdaten.Label.Label", null)
                        .WithMany()
                        .HasForeignKey("LabelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MyMusic.Domain.DomainModels.Sammlung.RecordTrack.RecordTrack", b =>
                {
                    b.HasOne("MyMusic.Domain.DomainModels.Stammdaten.Artist.Artist", null)
                        .WithMany()
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyMusic.Domain.DomainModels.Stammdaten.Genre.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyMusic.Domain.DomainModels.Sammlung.Record.Record", null)
                        .WithMany()
                        .HasForeignKey("RecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyMusic.Domain.DomainModels.Stammdaten.Label.Label", b =>
                {
                    b.HasOne("MyMusic.Domain.DomainModels.Stammdaten.Country.Country", null)
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
