global using System.Linq.Expressions;
global using System.Net;
global using FluentValidation;
global using FluentValidation.Results;
global using Microsoft.Extensions.DependencyInjection;
global using MyMusic.Application.Common.CQRS;
global using MyMusic.Application.Common.CQRS.Validation;
global using MyMusic.Application.Common.Exceptions;
global using MyMusic.Application.Common.Exceptions.ExceptionManager;
global using MyMusic.Application.Common.Services;
global using MyMusic.Application.DependencyInjection;
global using MyMusic.Application.Features.Integration.Discogs.Queries.GetRelease;
global using MyMusic.Application.Features.Integration.Discogs.Queries.Search;
global using MyMusic.Application.Features.Integration.Discogs.ResponseDtos;
global using MyMusic.Application.Features.Integration.Discogs.ResponseDtos.Builder;
global using MyMusic.Application.Features.Stammdaten.Artist.Commands.Create;
global using MyMusic.Application.Features.Stammdaten.Artist.Commands.Delete;
global using MyMusic.Application.Features.Stammdaten.Artist.Commands.Update;
global using MyMusic.Application.Features.Stammdaten.Artist.Queries.GetAll;
global using MyMusic.Application.Features.Stammdaten.Artist.Queries.GetById;
global using MyMusic.Application.Features.Stammdaten.Artist.Queries.GetPaged;
global using MyMusic.Application.Features.Stammdaten.Artist.ResponseDtos;
global using MyMusic.Application.Features.Stammdaten.Artist.ResponseDtos.Builder;
global using MyMusic.Application.Features.Stammdaten.Country.Queries.GetAll;
global using MyMusic.Application.Features.Stammdaten.Country.ResponseDtos;
global using MyMusic.Application.Features.Stammdaten.Country.ResponseDtos.Builder;
global using MyMusic.Application.Features.Stammdaten.Genre.Commands.Create;
global using MyMusic.Application.Features.Stammdaten.Genre.Commands.Delete;
global using MyMusic.Application.Features.Stammdaten.Genre.Commands.Update;
global using MyMusic.Application.Features.Stammdaten.Genre.Queries.GetAll;
global using MyMusic.Application.Features.Stammdaten.Genre.Queries.GetById;
global using MyMusic.Application.Features.Stammdaten.Genre.Queries.GetPaged;
global using MyMusic.Application.Features.Stammdaten.Genre.ResponseDtos;
global using MyMusic.Application.Features.Stammdaten.Genre.ResponseDtos.Builder;
global using MyMusic.Application.Features.Stammdaten.Label.Commands.Create;
global using MyMusic.Application.Features.Stammdaten.Label.Commands.Delete;
global using MyMusic.Application.Features.Stammdaten.Label.Commands.Update;
global using MyMusic.Application.Features.Stammdaten.Label.Queries.GetAll;
global using MyMusic.Application.Features.Stammdaten.Label.Queries.GetById;
global using MyMusic.Application.Features.Stammdaten.Label.Queries.GetPaged;
global using MyMusic.Application.Features.Sammlung.Dashboard.Queries.GetDashboard;
global using MyMusic.Application.Features.Sammlung.Dashboard.ResponseDtos;
global using MyMusic.Application.Features.Sammlung.Dashboard.ResponseDtos.Builder;
global using MyMusic.Application.Features.Sammlung.Record.Commands.Create;
global using MyMusic.Application.Features.Sammlung.Record.Commands.Delete;
global using MyMusic.Application.Features.Sammlung.Record.Commands.Update;
global using MyMusic.Application.Features.Sammlung.Record.Commands.UploadCover;
global using MyMusic.Application.Features.Sammlung.Record.Queries.GetById;
global using MyMusic.Application.Features.Sammlung.Record.Queries.GetPaged;
global using MyMusic.Application.Features.Sammlung.Record.ResponseDtos;
global using MyMusic.Application.Features.Sammlung.Record.ResponseDtos.Builder;
global using MyMusic.Application.Features.Sammlung.RecordTrack.Commands.Create;
global using MyMusic.Application.Features.Sammlung.RecordTrack.Commands.Delete;
global using MyMusic.Application.Features.Sammlung.RecordTrack.Commands.Update;
global using MyMusic.Application.Features.Sammlung.RecordTrack.ResponseDtos;
global using MyMusic.Application.Features.Sammlung.RecordTrack.ResponseDtos.Builder;
global using MyMusic.Application.Features.Sammlung.Search.Queries.GetPaged;
global using MyMusic.Application.Features.Sammlung.Search.ResponseDtos;
global using MyMusic.Application.Features.Sammlung.Search.ResponseDtos.Builder;
global using MyMusic.Application.Features.Stammdaten.Label.ResponseDtos;
global using MyMusic.Application.Features.Stammdaten.Label.ResponseDtos.Builder;
global using MyMusic.Application.Features.System.CurrentUser.Commands.ChangePassword;
global using MyMusic.Application.Features.System.CurrentUser.Commands.UpdateEmail;
global using MyMusic.Application.Features.System.CurrentUser.Queries.GetCurrentUser;
global using MyMusic.Application.Features.System.CurrentUser.ResponseDtos;
global using MyMusic.Application.Features.System.CurrentUser.ResponseDtos.Builder;
global using MyMusic.Application.Features.Verwaltung.Admin.Commands.Delete;
global using MyMusic.Application.Features.Verwaltung.Admin.Queries.GetPaged;
global using MyMusic.Application.Features.Verwaltung.Admin.ResponseDtos;
global using MyMusic.Application.Features.Verwaltung.Admin.ResponseDtos.Builder;
global using MyMusic.Application.Tests.Common.CQRS.TestDoubles;
global using MyMusic.Application.Tests.Common.CQRS.Validation.TestDoubles;
global using MyMusic.Domain.Contracts.Repository;
global using ArtistEntity = MyMusic.Domain.DomainModels.Stammdaten.Artist.Artist;
global using CountryEntity = MyMusic.Domain.DomainModels.Stammdaten.Country.Country;
global using GenreEntity = MyMusic.Domain.DomainModels.Stammdaten.Genre.Genre;
global using LabelEntity = MyMusic.Domain.DomainModels.Stammdaten.Label.Label;
global using RecordEntity = MyMusic.Domain.DomainModels.Sammlung.Record.Record;
global using RecordFormat = MyMusic.Domain.DomainModels.Sammlung.Record.RecordFormat;
global using RecordCondition = MyMusic.Domain.DomainModels.Sammlung.Record.RecordCondition;
global using RecordTrackEntity = MyMusic.Domain.DomainModels.Sammlung.RecordTrack.RecordTrack;
global using ValidationException = MyMusic.Application.Common.Exceptions.ValidationException;
