global using System.Linq.Expressions;
global using FluentValidation;
global using FluentValidation.Results;
global using Microsoft.Extensions.DependencyInjection;
global using MyMusic.Application.Common.CQRS;
global using MyMusic.Application.Common.CQRS.Validation;
global using MyMusic.Application.Common.Exceptions;
global using MyMusic.Application.Common.Exceptions.ExceptionManager;
global using MyMusic.Application.Common.Services;
global using MyMusic.Application.DependencyInjection;
global using MyMusic.Application.Features.Stammdaten.Country.Queries.GetAll;
global using MyMusic.Application.Features.Stammdaten.Country.ResponseDtos;
global using MyMusic.Application.Features.Stammdaten.Country.ResponseDtos.Builder;
global using MyMusic.Application.Features.Stammdaten.Genre.Commands.Create;
global using MyMusic.Application.Features.Stammdaten.Genre.Commands.Delete;
global using MyMusic.Application.Features.Stammdaten.Genre.Commands.Update;
global using MyMusic.Application.Features.Stammdaten.Genre.Queries.GetById;
global using MyMusic.Application.Features.Stammdaten.Genre.Queries.GetPaged;
global using MyMusic.Application.Features.Stammdaten.Genre.ResponseDtos;
global using MyMusic.Application.Features.Stammdaten.Genre.ResponseDtos.Builder;
global using MyMusic.Application.Features.System.CurrentUser.Queries.GetCurrentUser;
global using MyMusic.Application.Features.System.CurrentUser.ResponseDtos;
global using MyMusic.Application.Features.System.CurrentUser.ResponseDtos.Builder;
global using MyMusic.Application.Tests.Common.CQRS.TestDoubles;
global using MyMusic.Application.Tests.Common.CQRS.Validation.TestDoubles;
global using MyMusic.Domain.Contracts.Repository;
global using CountryEntity = MyMusic.Domain.DomainModels.Stammdaten.Country.Country;
global using GenreEntity = MyMusic.Domain.DomainModels.Stammdaten.Genre.Genre;
global using ValidationException = MyMusic.Application.Common.Exceptions.ValidationException;
