import { Country } from '../../shared/country/country';

/**
 * Discogs liefert das Herkunftsland eines Release als englischen Freitext, unsere
 * `country`-Stammdaten führen dagegen deutsche Namen mit ISO-3166-1-alpha-2-Code (siehe Wiki
 * `country-referenzdaten.md`). Diese Tabelle übersetzt den üblichen englischen Ländernamen in
 * den passenden Code. Regionale Discogs-Sammelbegriffe (z. B. "Europe", "UK & Europe") und bei
 * uns nicht geführte historische Staaten (z. B. "Czechoslovakia", "USSR") tauchen absichtlich
 * nicht auf — dafür bleibt der Aufrufer ohne Treffer.
 */
const DISCOGS_COUNTRY_TO_ISO_CODE: Record<string, string> = {
  egypt: 'EG',
  albania: 'AL',
  algeria: 'DZ',
  andorra: 'AD',
  angola: 'AO',
  anguilla: 'AI',
  antarctica: 'AQ',
  'antigua and barbuda': 'AG',
  'equatorial guinea': 'GQ',
  argentina: 'AR',
  armenia: 'AM',
  aruba: 'AW',
  azerbaijan: 'AZ',
  ethiopia: 'ET',
  australia: 'AU',
  bahamas: 'BS',
  bahrain: 'BH',
  bangladesh: 'BD',
  barbados: 'BB',
  belgium: 'BE',
  belize: 'BZ',
  benin: 'BJ',
  bermuda: 'BM',
  bhutan: 'BT',
  myanmar: 'MM',
  burma: 'MM',
  bolivia: 'BO',
  'bosnia and herzegovina': 'BA',
  botswana: 'BW',
  'bouvet island': 'BV',
  brazil: 'BR',
  'british indian ocean territory': 'IO',
  brunei: 'BN',
  bulgaria: 'BG',
  'burkina faso': 'BF',
  burundi: 'BI',
  chile: 'CL',
  china: 'CN',
  'christmas island': 'CX',
  'cook islands': 'CK',
  'costa rica': 'CR',
  denmark: 'DK',
  germany: 'DE',
  djibouti: 'DJ',
  dominica: 'DM',
  'dominican republic': 'DO',
  ecuador: 'EC',
  'el salvador': 'SV',
  'ivory coast': 'CI',
  "cote d'ivoire": 'CI',
  eritrea: 'ER',
  estonia: 'EE',
  'falkland islands': 'FK',
  'faroe islands': 'FO',
  fiji: 'FJ',
  finland: 'FI',
  france: 'FR',
  'french guiana': 'GF',
  'french polynesia': 'PF',
  'french southern territories': 'TF',
  gabon: 'GA',
  gambia: 'GM',
  georgia: 'GE',
  ghana: 'GH',
  gibraltar: 'GI',
  grenada: 'GD',
  greece: 'GR',
  greenland: 'GL',
  'united kingdom': 'GB',
  uk: 'GB',
  guadeloupe: 'GP',
  guam: 'GU',
  guatemala: 'GT',
  guinea: 'GN',
  'guinea-bissau': 'GW',
  guyana: 'GY',
  haiti: 'HT',
  'heard island and mcdonald islands': 'HM',
  honduras: 'HN',
  'hong kong': 'HK',
  india: 'IN',
  indonesia: 'ID',
  iraq: 'IQ',
  iran: 'IR',
  ireland: 'IE',
  iceland: 'IS',
  israel: 'IL',
  italy: 'IT',
  jamaica: 'JM',
  japan: 'JP',
  yemen: 'YE',
  jordan: 'JO',
  yugoslavia: 'YU',
  'cayman islands': 'KY',
  cambodia: 'KH',
  cameroon: 'CM',
  canada: 'CA',
  'cape verde': 'CV',
  kazakhstan: 'KZ',
  kenya: 'KE',
  kyrgyzstan: 'KG',
  kiribati: 'KI',
  'cocos islands': 'CC',
  colombia: 'CO',
  comoros: 'KM',
  congo: 'CG',
  'congo, democratic republic of': 'CD',
  'democratic republic of the congo': 'CD',
  croatia: 'HR',
  cuba: 'CU',
  kuwait: 'KW',
  laos: 'LA',
  lesotho: 'LS',
  latvia: 'LV',
  lebanon: 'LB',
  liberia: 'LR',
  libya: 'LY',
  liechtenstein: 'LI',
  lithuania: 'LT',
  luxembourg: 'LU',
  macau: 'MO',
  madagascar: 'MG',
  malawi: 'MW',
  malaysia: 'MY',
  maldives: 'MV',
  mali: 'ML',
  malta: 'MT',
  'northern mariana islands': 'MP',
  morocco: 'MA',
  'marshall islands': 'MH',
  martinique: 'MQ',
  mauritania: 'MR',
  mauritius: 'MU',
  mayotte: 'YT',
  macedonia: 'MK',
  'north macedonia': 'MK',
  mexico: 'MX',
  micronesia: 'FM',
  mozambique: 'MZ',
  moldova: 'MD',
  monaco: 'MC',
  mongolia: 'MN',
  montserrat: 'MS',
  namibia: 'NA',
  nauru: 'NR',
  nepal: 'NP',
  'new caledonia': 'NC',
  'new zealand': 'NZ',
  nicaragua: 'NI',
  netherlands: 'NL',
  'netherlands antilles': 'AN',
  niger: 'NE',
  nigeria: 'NG',
  niue: 'NU',
  'north korea': 'KP',
  'norfolk island': 'NF',
  norway: 'NO',
  oman: 'OM',
  austria: 'AT',
  pakistan: 'PK',
  palestine: 'PS',
  palau: 'PW',
  panama: 'PA',
  'papua new guinea': 'PG',
  paraguay: 'PY',
  peru: 'PE',
  philippines: 'PH',
  pitcairn: 'PN',
  poland: 'PL',
  portugal: 'PT',
  'puerto rico': 'PR',
  qatar: 'QA',
  reunion: 'RE',
  rwanda: 'RW',
  romania: 'RO',
  russia: 'RU',
  'saint lucia': 'LC',
  zambia: 'ZM',
  'american samoa': 'AS',
  samoa: 'WS',
  'san marino': 'SM',
  'sao tome and principe': 'ST',
  'saudi arabia': 'SA',
  sweden: 'SE',
  switzerland: 'CH',
  senegal: 'SN',
  seychelles: 'SC',
  'sierra leone': 'SL',
  singapore: 'SG',
  slovakia: 'SK',
  slovenia: 'SI',
  'solomon islands': 'SB',
  somalia: 'SO',
  'south georgia': 'GS',
  spain: 'ES',
  'sri lanka': 'LK',
  'saint helena': 'SH',
  'saint kitts and nevis': 'KN',
  'saint pierre and miquelon': 'PM',
  'saint vincent and the grenadines': 'VC',
  'south korea': 'KR',
  'south africa': 'ZA',
  sudan: 'SD',
  suriname: 'SR',
  'svalbard and jan mayen': 'SJ',
  swaziland: 'SZ',
  eswatini: 'SZ',
  syria: 'SY',
  tajikistan: 'TJ',
  taiwan: 'TW',
  tanzania: 'TZ',
  thailand: 'TH',
  'east timor': 'TP',
  togo: 'TG',
  tokelau: 'TK',
  tonga: 'TO',
  'trinidad and tobago': 'TT',
  chad: 'TD',
  'czech republic': 'CZ',
  czechia: 'CZ',
  tunisia: 'TN',
  turkey: 'TR',
  turkmenistan: 'TM',
  'turks and caicos islands': 'TC',
  tuvalu: 'TV',
  uganda: 'UG',
  ukraine: 'UA',
  hungary: 'HU',
  uruguay: 'UY',
  uzbekistan: 'UZ',
  vanuatu: 'VU',
  'vatican city': 'VA',
  vatican: 'VA',
  venezuela: 'VE',
  'united arab emirates': 'AE',
  'united states': 'US',
  'united states of america': 'US',
  us: 'US',
  usa: 'US',
  vietnam: 'VN',
  'british virgin islands': 'VG',
  'us virgin islands': 'VI',
  'wallis and futuna': 'WF',
  belarus: 'BY',
  'western sahara': 'EH',
  'central african republic': 'CF',
  zimbabwe: 'ZW',
  cyprus: 'CY',
};

/**
 * Löst den von Discogs gelieferten Ländertext auf die passende {@link Country} aus den lokalen
 * Stammdaten auf. `null` bei fehlendem Discogs-Wert, keinem Tabellentreffer oder fehlendem
 * Country-Datensatz mit dem ermittelten Code.
 */
export function resolveDiscogsCountryId(
  discogsCountry: string | null,
  countries: Country[],
): number | null {
  if (!discogsCountry) {
    return null;
  }

  const isoCode = DISCOGS_COUNTRY_TO_ISO_CODE[discogsCountry.trim().toLowerCase()];

  if (!isoCode) {
    return null;
  }

  const country = countries.find((candidate) => candidate.code.toUpperCase() === isoCode);

  return country?.id ?? null;
}
