global using System.Reflection;
global using FluentValidation;
global using FluentValidation.Results;
global using Microsoft.Extensions.DependencyInjection;
global using MyMusic.Application.Common.CQRS;
global using MyMusic.Application.Common.CQRS.Validation;
global using MyMusic.Application.Common.Exceptions;
global using MyMusic.Application.Common.Exceptions.ExceptionManager;
global using MyMusic.Application.Common.Services;
global using MyMusic.Application.Features.Stammdaten.Artist.ResponseDtos;
global using MyMusic.Application.Features.Stammdaten.Artist.ResponseDtos.Builder;
global using MyMusic.Application.Features.Stammdaten.Country.ResponseDtos;
global using MyMusic.Application.Features.Stammdaten.Country.ResponseDtos.Builder;
global using MyMusic.Application.Features.Stammdaten.Genre.ResponseDtos;
global using MyMusic.Application.Features.Stammdaten.Genre.ResponseDtos.Builder;
global using MyMusic.Application.Features.Sammlung.Record.ResponseDtos;
global using MyMusic.Application.Features.Sammlung.Record.ResponseDtos.Builder;
global using MyMusic.Application.Features.Sammlung.RecordTrack.ResponseDtos;
global using MyMusic.Application.Features.Sammlung.RecordTrack.ResponseDtos.Builder;
global using MyMusic.Application.Features.Stammdaten.Label.ResponseDtos;
global using MyMusic.Application.Features.Stammdaten.Label.ResponseDtos.Builder;
global using MyMusic.Application.Features.System.CurrentUser.ResponseDtos;
global using MyMusic.Application.Features.System.CurrentUser.ResponseDtos.Builder;
global using MyMusic.Domain.Contracts.Repository;
global using ArtistEntity = MyMusic.Domain.DomainModels.Stammdaten.Artist.Artist;
global using CountryEntity = MyMusic.Domain.DomainModels.Stammdaten.Country.Country;
global using GenreEntity = MyMusic.Domain.DomainModels.Stammdaten.Genre.Genre;
global using LabelEntity = MyMusic.Domain.DomainModels.Stammdaten.Label.Label;
global using RecordEntity = MyMusic.Domain.DomainModels.Sammlung.Record.Record;
global using RecordFormat = MyMusic.Domain.DomainModels.Sammlung.Record.RecordFormat;
global using RecordCondition = MyMusic.Domain.DomainModels.Sammlung.Record.RecordCondition;
global using RecordTrackEntity = MyMusic.Domain.DomainModels.Sammlung.RecordTrack.RecordTrack;
global using ValidationException = MyMusic.Application.Common.Exceptions.ValidationException;
