global using System.Reflection;
global using FluentValidation;
global using FluentValidation.Results;
global using Microsoft.Extensions.DependencyInjection;
global using MyMusic.Application.Common.CQRS;
global using MyMusic.Application.Common.CQRS.Validation;
global using MyMusic.Application.Common.Exceptions;
global using MyMusic.Application.Common.Exceptions.ExceptionManager;
global using MyMusic.Application.Common.Services;
global using MyMusic.Application.Features.Stammdaten.Country.ResponseDtos;
global using MyMusic.Application.Features.Stammdaten.Country.ResponseDtos.Builder;
global using MyMusic.Application.Features.Stammdaten.Genre.ResponseDtos;
global using MyMusic.Application.Features.Stammdaten.Genre.ResponseDtos.Builder;
global using MyMusic.Application.Features.System.CurrentUser.ResponseDtos;
global using MyMusic.Application.Features.System.CurrentUser.ResponseDtos.Builder;
global using MyMusic.Domain.Contracts.Repository;
global using CountryEntity = MyMusic.Domain.DomainModels.Stammdaten.Country.Country;
global using GenreEntity = MyMusic.Domain.DomainModels.Stammdaten.Genre.Genre;
global using ValidationException = MyMusic.Application.Common.Exceptions.ValidationException;
